### ISSUE TITLE
Setup github labels

### ISSUE THREAD

**Issue by FallingSnow** [tuffyestates/web-client#2]
We need someone to setup a labeling system. This is a good example:
https://github.com/servo/servo/issues
Here is a description of what each label means:
https://github.com/servo/servo/wiki/Tag-label-names-and-definitions

Please set this up as these labels. You can do that [here](https://github.com/tuffyestates/web-client/labels). You can delete the default labels as you see fit.

**Comment by FallingSnow** [comment]
We now need to copy these labels to the tuffyestates/backend repository. There are tools that can copy github labels between repositories, otherwise we can just copy and paste each label's name, description, and color code to the backend repository.

**Comment by FallingSnow** [comment]
We need to add area labels as well (these will be different for the backend repository). For example,
* A-style (Having to do with CSS)
* A-design (Having to do with HTML/format the webpage)
* A-ux (Having to do with user experience, mostly user workflow)
* A-doc/dev (Documentation or developer experience)

Also need platform labels, this is to identify issues unique to a specific platform:
* P-chrom (Chromium and Chrome)
* P-firefox (Firefox)
* P-safari (Safari)
* P-edge (Microsoft Edge)

**Comment by vuskeedoo** [comment]
Microsoft edge is being discontinued. ❌ 

I added the rest of the tags
